site_name: Company Docs
site_url: https://yourdomain.github.io/docs
site_description: Our company documentation hub

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Handbook:
    - Welcome: handbook/index.md
    - Onboarding: handbook/onboarding.md
    - Company Values: handbook/values.md
    - Time Off Policy: handbook/time-off.md
  - Engineering:
    - Overview: engineering/index.md
    - Development Setup: engineering/setup.md
    - Deployment Guide: engineering/deployment.md
    - Code Standards: engineering/standards.md
  - Processes:
    - How We Work: processes/index.md
    - Meeting Guidelines: processes/meetings.md
    - Decision Making: processes/decisions.md
    - Contributing: processes/contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername